### ISSUE TITLE
Typo in documentaion

### ISSUE THREAD

**Issue by gstoychev-despark** [videogorillas/vgplayer-api#5]
https://github.com/videogorillas/vgplayer-api/blob/master/Player.md#Player_seekToSec

`seekToSec` method missing, the `seekSec` working as expected

**Comment by chugai** [comment]
fixed. thanks

**Comment by VanTanev** [comment]
@chugai you missed typos here: https://github.com/videogorillas/vgplayer-api/blob/master/Player.md#playback-control-methods

Also, `seekToFrame` => `seekFrame`

**Comment by chugai** [comment]
Thanks

вівторок, 29 березня 2016 р. користувач Ivan Tanev notifications@github.com
написав:
